### ISSUE TITLE
[TIL] JavaScript의 this | 42Log

### ISSUE THREAD

**Issue by 42KIM** [42KIM/42KIM.github.io#4]
…

https://42kim.github.io/TIL/js_this/

**Comment by 42KIM** [comment]
ㅎㅇ

**Comment by manudeli** [comment]
요우 42님 잘 배우고 가요

**Comment by limkhl** [comment]
42님... 이거 대박 아티클이네요... 이해가 다 되어버린 것 같습니다... 짱입니다...

**Comment by 42KIM** [comment]
@manudeli 이 누추한 곳에는 도대체 어떻게 오신거죠 ㅋㅋ

**Comment by 42KIM** [comment]
@limkhl 이해하시는 데에 조금이라도 도움이 되었다면 다행입니다..!

**Comment by manudeli** [comment]
> @manudeli 이 누추한 곳에는 도대체 어떻게 오신거죠 ㅋ

@grighth12
권정희정희상이 소개시켜줬어요 최고의 this article이라고! 말그대로 최고네요
